### ISSUE TITLE
[Combinator] Fix 1 legendary pick

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/herodamage#1]
If you only select one legendary, it should give you the list of combinations that contains at least this legendary. 
ATM, this gives you nothing

**Comment by Mystler** [comment]
Closing this again after some discussion on Discord. The legendary filter is supposed to allow you to select the legendaries you have and thus we will leave it to only display valid combinations for such a selection. With PR gear setups, single legendary setups will be shown as you would expect. It may only look a bit confusing because Tier sims do not have results for just one legendary.
