### ISSUE TITLE
[Relics/Trinkets] Use % increase metric

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/herodamage#35]
This will make relic sims more globally comparable.

**Comment by Mystler** [comment]
Aethys implemented DPS Gain bars in https://github.com/Ravenholdt-TC/SimcScripts/commit/7a4a5d971d0a37c1b370243a438cd16bfe10e82d.

Leaving this open because we should probably consider switching the whole chart over to a % metric, with % values (likely alongside the current absolutes) in the tooltip. I guess this also goes for the trinkets.

**Comment by aethys256** [comment]
I agree, I think with our current implementations we would have to make two series, one with % increase the other with the absolute one.
That would make it easy to implement for both charts I guess.
Else we should already look at D3 if it's too much work since it's likely that after 4D plots implementation we'll switch everything to that (or a lib that implement it like Plotly).

**Comment by Mystler** [comment]
Changed to use % metric by default with absolute increases in tooltips in https://github.com/SimCMinMax/herodamage/compare/2b8a7994a01d...c6c740c.
