### ISSUE TITLE
[Scripts] Unify Trinket and Relic profiles

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/herodamage#37]
Once the Relic script rework is pushed and Relic Sim requires only the base profile (like Trinkets), I think we should refactor the profiles for Trinkets and Relics to use the same template files, so we don't have to maintain them twice.

**Comment by aethys256** [comment]
I feel like we should just scrap the profiles which use simc default and retrieves it from simc folder.
If it's a different profiles (that isn't in default simc ones because different) then we fetch it from the ones on the repo.

We could let a way to add overrides for the simc default aswell, so we don't have to make a dedicated profile just for some simple override.

**Comment by Mystler** [comment]
Unified templates for non-combinator profiles in https://github.com/Ravenholdt-TC/SimcScripts/commit/bfc30167fc209ab2b37620f7734a2ff6944a8adb.
